### PR TITLE
listener functions. wallet balance

### PR DESCRIPTION
**Pull request by benjiqq**
some suggestions. 

* adds subscribeToRaydiumPools in separate function
* adds subscribeToOpenbook in separate function
* adds subscribeAutosell in separate function
* shows wallet balance at startup. should add wSOL (TODO)
* try catch if wallet cant be read

### CODE REVIEW

**Comment by baiyibo** [comment]
let amountharf = BigInt(divCeil(parseBigNumberish(amount), new BN(2)).toString());

Please help me, guys. I've been stuck for a while now. I just want to modify the amount to sell to be half of the token amount in the account. Why do I keep getting errors?
image
image

**Comment by shakilkhan1801** [comment]
I have sol in my wallet but I couldn't swap Sol to WSOL anywhere despite trying. And meanwhile the code is telling me I don't have Sol in my wallet. Please give option to use native sol instead of Wsol.

**Comment by benjiqq** [comment]
"I have sol in my wallet but I couldn't swap Sol to WSOL anywhere despite trying. And meanwhile the code is telling me I don't have Sol in my wallet. Please give option to use native sol instead of Wsol."

unrelated to this PR? file an issue for feature request

**Comment by virtuman** [comment]
@benjiqq - looks like you are checking for SOL balance, that is then output on the screen, instead of WSOL ? I was under the impression that bot is using WSOL or am I missing some point here?

**Comment by benjiqq** [comment]
@virtuman correct thanks, should fix. I want to add a SOL feature to avoid manual wrapping.

**Comment by earnbuzz** [comment]
It's a nice bot, but I'm disappointed it wasn't written using node.js or python. Please give node.js version if possible.

**Comment by earnbuzz** [comment]
Can this bot check liquidity lock and how much %?
Out of all the tokens I bought last night with this bot, I was only able to sell one token. And all the remaining tokens are rug.

**Comment by DevSolana** [comment]
> Can this bot check liquidity lock and how much %? Out of all the tokens I bought last night with this bot, I was only able to sell one token. And all the remaining tokens are rug.

Stop spamming all pull request

**Comment by wang88139** [comment]
Please join the top 10 and the number of holdings does not exceed 30%.

**Comment by TYRANTHOSAURUS** [comment]
I added this to get WSOL balance, i put this in a state to manage buy/sell transactions and calculate gains.

```
async function getTokenBalance(walletPublicKey: PublicKey): Promise<number | null> {
  let mintAddress = undefined;
  if (QUOTE_MINT === 'WSOL') {
    mintAddress = 'So11111111111111111111111111111111111111112';
  }
  if (QUOTE_MINT === 'USDC') {
    mintAddress = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
  }
  if (!mintAddress) return null;

  const walletPubKey = new PublicKey(walletPublicKey);
  const tokenMintPubKey = new PublicKey(mintAddress);

  // Compute the associated token account address
  const associatedTokenAddress = await getAssociatedTokenAddress(tokenMintPubKey, walletPubKey);

  try {
    // Query the balance
    const balanceResult = await solanaConnection.getTokenAccountBalance(associatedTokenAddress);
    return balanceResult.value.uiAmount;
  } catch (error) {
    console.error(`Could not fetch balance for account ${associatedTokenAddress.toString()}: ${error}`);
    return null;
  }
}
```

Then in init()
```

async function init(): Promise<void> {
  logger.level = LOG_LEVEL;

  // get wallet
  wallet = Keypair.fromSecretKey(bs58.decode(PRIVATE_KEY));
  logger.info(`Wallet Address: ${wallet.publicKey}`);

  // get wallet balance for QUOTE_MINT token
  const balance = await getTokenBalance(wallet.publicKey);

  // Rest of init code
  }
```

**Pull request closed without merging**
