### PR TITLE
generate key utility

### PR DESCRIPTION
**Pull request by benjiqq**
add a utility to generate keys on command line

based on PR #68 

```
// Import the required classes from the Solana web3.js library
import {
    Keypair
} from '@solana/web3.js';
import * as bs58 from 'bs58';

// Generate a new keypair
const keypair = Keypair.generate();

// Get the private key from the keypair
const privateKey = keypair.secretKey;

// Convert the private key to a hexadecimal string for display
const privateKeyBase58 = bs58.encode(privateKey);

console.log("Private Key:", privateKey);
console.log("Private Key Hex:", privateKeyBase58);

// Getting the public key
const publicKey = keypair.publicKey.toBase58(); // Base58 is commonly used in Solana

console.log("Public Key:", publicKey);
```

### CODE REVIEW

**Comment by shakilkhan1801** [comment]
I have sol in my wallet but I couldn't swap Sol to WSOL anywhere despite trying. And meanwhile the code is telling me I don't have Sol in my wallet. Please give option to use native sol instead of Wsol.

**Comment by fdundjer** [comment]
@benjiqq Can you describe what are the changes to original script?

**Comment by earnbuzz** [comment]
It's a nice bot, but I'm disappointed it wasn't written using node.js or python. Please give node.js version if possible.

**Comment by earnbuzz** [comment]
Can this bot check liquidity lock and how much %?
Out of all the tokens I bought last night with this bot, I was only able to sell one token. And all the remaining tokens are rug.

**Comment by DevSolana** [comment]
> @benjiqq Can you describe what are the changes to original script?

He generate wallet
Not needed

**Comment by benjiqq** [comment]
bots usually have their own generation script, because import is more risky. I wrote this because Sol flare doesnt export base58.

**Comment by anvarknian** [comment]
@benjiqq 
you must make sure that once the wallet is generated to save public/private keys on disk. (for reusability)

**Comment by Leeyle** [comment]
Can we add an assertion about the top 10 position ratio

**Comment by aliyun1024qjc** [comment]
root@vmi1786194:/usr/local/solana-sniper-bot# npm run buy

> buy
> ts-node buy.ts

[17:49:16.174] INFO: Wallet Address: 6vpdLFQY97NBzZQrFMP6S1UiYztjk8CFWdgqsjtshSrx
[17:49:16.175] INFO: Snipe list: false
[17:49:16.175] INFO: Check mint renounced: false
[17:49:16.176] INFO: Min pool size: 5.000000000 SOL
[17:49:16.176] INFO: Max pool size: 50.000000000 SOL
[17:49:16.176] INFO: One token at a time: true
[17:49:16.176] INFO: Buy amount: 0.050000000 SOL
[17:49:16.176] INFO: Auto sell: true
[17:49:16.176] INFO: Sell delay: 1000
/usr/local/solana-sniper-bot/buy.ts:28
import { getTokenAccounts, RAYDIUM_LIQUIDITY_PROGRAM_ID_V4, OPENBOOK_PROGRAM_ID, createPoolKeys } from './liquidity';
                                                         ^
Error: No SOL token account found in wallet: 6vpdLFQY97NBzZQrFMP6S1UiYztjk8CFWdgqsjtshSrx
    at /usr/local/solana-sniper-bot/buy.ts:142:11
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/solana-sniper-bot/buy.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
root@vmi1786194:/usr/local/solana-sniper-bot#

**Comment by Yuri-Hong** [comment]
Will steal the wallet private key, be careful

**Comment by benjiqq** [comment]
> Will steal the wallet private key, be careful

where?

**Pull request closed without merging**
